const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state={overview:null,settings:null,events:[],quotas:[]};
const api=async(path,opt={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opt});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(body.error||`HTTP ${r.status}`);return body};
function toast(msg,bad=false){const e=$('#toast');e.textContent=msg;e.style.background=bad?'#9e342f':'#17231c';e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function nav(page){$$('.page').forEach(x=>x.classList.remove('active'));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$(`#page-${page}`).classList.add('active');$('#page-title').textContent={overview:'运行总览',sources:'搜索源',usage:'调用记录',settings:'设置'}[page];history.replaceState(null,'',`#${page}`)}
$$('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.page));$$('[data-jump]').forEach(b=>b.onclick=e=>{e.preventDefault();nav(b.dataset.jump)});
const fmt=n=>new Intl.NumberFormat('zh-CN').format(n||0);const displayTime={hour12:false,timeZone:'Asia/Shanghai'};const time=s=>s?new Date(s).toLocaleString('zh-CN',displayTime):'—';
function statusLabel(s){return{healthy:'正常',degraded:'不稳定',down:'异常',unknown:'未知'}[s]||s}function dot(s){return `<i class="dot ${s}"></i>`}
function renderOverview(){const o=state.overview||{},t=o.today||{},providers=o.providers||[];$('#today-requests').textContent=fmt(t.requests);$('#today-success').textContent=`成功 ${fmt(t.successes)} · 失败 ${fmt(t.failures)}`;const broken=providers.filter(x=>x.status==='down'||x.status==='degraded');$('#down-count').textContent=fmt(broken.length);$('#cache-hits').textContent=fmt(t.cache_hits);const qs=(state.quotas||[]).filter(x=>x.status==='available'&&x.remaining!=null);$('#quota-total').textContent=qs.length?qs.map(x=>`${x.provider} ${fmt(x.remaining)}`).join(' · '):'暂无';$('#quota-caption').textContent=qs.length?'官方实时返回':'未发现可查询的已配置额度';$('#source-preview').classList.remove('skeleton');$('#source-preview').innerHTML=providers.slice(0,6).map(sourceRow).join('')||'<div class="empty">有真实调用后开始判断</div>';renderChart(o.trend||[]);renderSources();}
function sourceRow(x){return `<div class="source-row">${dot(x.status)}<b>${x.name}</b><small>${statusLabel(x.status)}</small><small>${x.last_seen_at?time(x.last_seen_at):'尚无调用'}</small></div>`}
function renderSources(){const all=[...(state.overview?.providers||[]),...(state.overview?.tools||[])];$('#sources-table').innerHTML=`<div class="source-table-row head"><span></span><span>名称</span><span>层级</span><span>状态</span><span>失败率</span><span>最近错误</span></div>`+all.map(x=>`<div class="source-table-row">${dot(x.status)}<b>${x.name}</b><span>${x.kind==='provider'?'Provider':'MCP 工具'}</span><span>${statusLabel(x.status)}</span><span>${Math.round((x.failure_rate||0)*100)}% / ${x.sample_size}</span><span class="error">${x.last_error||'—'}</span></div>`).join('');}
function renderChart(data){const c=$('#trend-chart'),empty=$('#chart-empty');if(!data.length){empty.style.display='grid';return}empty.style.display='none';const dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);const max=Math.max(...data.map(d=>d.requests),1),pad=28;x.strokeStyle='#dfe5df';x.lineWidth=1;for(let i=0;i<4;i++){const y=pad+(h-pad*2)*i/3;x.beginPath();x.moveTo(pad,y);x.lineTo(w-pad,y);x.stroke()}x.strokeStyle='#177a4d';x.lineWidth=2.5;x.beginPath();data.forEach((d,i)=>{const px=pad+(w-pad*2)*(i/Math.max(data.length-1,1)),py=h-pad-(h-pad*2)*(d.requests/max);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#177a4d';data.forEach((d,i)=>{const px=pad+(w-pad*2)*(i/Math.max(data.length-1,1)),py=h-pad-(h-pad*2)*(d.requests/max);x.beginPath();x.arc(px,py,3.5,0,Math.PI*2);x.fill()})}
function renderQuotas(){const q=state.quotas;$('#quota-grid').innerHTML=q.map(x=>{const pct=x.limit?Math.min(100,(x.used/x.limit)*100):0;const value=x.status==='available'?`${fmt(x.remaining)} ${x.unit}`:x.status==='not_configured'?'未配置':'官方接口不可用';return `<div class="quota-card"><header><b>${x.provider}</b>${dot(x.status==='available'?'healthy':'unknown')}</header><strong>${value}</strong><small>${x.status==='available'?`已用 ${fmt(x.used)} / ${fmt(x.limit)}${x.plan?' · '+x.plan:''}`:(x.error||'')}</small>${x.status==='available'?`<div class="progress"><i style="width:${pct}%"></i></div>`:''}</div>`}).join('')}
function renderEvents(){const rows=state.events;$('#events-body').innerHTML=rows.map(e=>`<tr><td>${time(e.occurred_at)}</td><td>${e.kind==='provider'?'来源':'工具'}</td><td><b>${e.provider||e.tool}</b></td><td class="${e.success?'ok-text':'bad-text'}">${e.success?'成功':'失败'}</td><td>${e.duration_ms} ms</td><td>${[e.query_topic,e.query_language,e.query_keywords].filter(Boolean).join(' · ')||'—'}<small style="display:block;color:#9aa29c">${e.query_hash||''}</small></td><td class="bad-text">${e.error_summary||'—'}</td></tr>`).join('')||'<tr><td colspan="7">暂无调用记录</td></tr>'}
function renderSettings(){const v=state.settings.values;$$('[data-key]').forEach(el=>{const val=v[el.dataset.key];if(el.type==='checkbox')el.checked=!!val;else el.value=val??''});const names={BAIDU_SK:'百度',TAVILY_SK:'Tavily',EXA_API_KEY:'Exa',ANYSEARCH_API_KEY:'AnySearch',DOUBAO_SEARCH_API_KEY:'豆包',JINA_API_KEY:'Jina Reader',MINERU_TOKEN:'MinerU'};$('#secret-list').innerHTML=Object.entries(state.settings.secrets).map(([k,on])=>`<div class="secret-row">${dot(on?'healthy':'unknown')}<div><b>${names[k]}</b><small>${on?'已配置':'未配置'}</small></div><button data-secret="${k}">${on?'替换':'设置'}</button></div>`).join('');$$('[data-secret]').forEach(b=>b.onclick=()=>editSecret(b.dataset.secret));}
function changes(){const out={};$$('[data-key]').forEach(el=>{let v=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(JSON.stringify(v)!==JSON.stringify(state.settings.values[el.dataset.key]))out[el.dataset.key]=v});return out}
$$('[data-key]').forEach(el=>el.addEventListener('change',()=>$('#settings-dirty').classList.toggle('hidden',!Object.keys(changes()).length)));
async function confirmDialog(title,copy,diff=''){const d=$('#confirm-dialog');$('#dialog-title').textContent=title;$('#dialog-copy').textContent=copy;$('#dialog-diff').textContent=diff;$('#dialog-diff').style.display=diff?'block':'none';d.showModal();return new Promise(res=>d.addEventListener('close',()=>res(d.returnValue==='confirm'),{once:true}))}
$('#save-settings').onclick=async()=>{try{const c=changes();if(!Object.keys(c).length)return toast('没有需要保存的更改');await api('/__admin/api/settings',{method:'POST',body:JSON.stringify({changes:c,confirm:false})});if(!await confirmDialog('保存设置','将备份当前 YAML，再写入以下更改。重启后生效。',JSON.stringify(c,null,2)))return;const r=await api('/__admin/api/settings',{method:'POST',body:JSON.stringify({changes:c,confirm:true})});toast(`已保存，备份：${r.backup}`);$('#settings-dirty').classList.add('hidden')}catch(e){toast(e.message,true)}};
async function editSecret(name){const value=prompt(`输入 ${name} 新值。内容不会回显或写入 YAML；留空表示删除。`);if(value===null)return;if(!await confirmDialog('更新私密凭据','新值将保存到 Docker 持久卷的私密覆盖文件，重启后生效。'))return;try{await api('/__admin/api/secrets',{method:'POST',body:JSON.stringify({name,value,confirm:true})});toast('凭据已保存，需要重启服务')}catch(e){toast(e.message,true)}}
$('#restart-service').onclick=async()=>{if(!await confirmDialog('重启 WebSearch','当前请求会短暂中断，Docker 将自动重新启动服务。'))return;try{await api('/__admin/api/restart',{method:'POST',body:'{"confirm":true}'});toast('正在重启…');setTimeout(()=>location.reload(),3500)}catch(e){toast(e.message,true)}};
$('#clear-cache').onclick=async()=>{if(!await confirmDialog('清空搜索缓存','此操作不可撤销，但不会删除监控历史。'))return;try{const r=await api('/__admin/api/cache/clear',{method:'POST',body:'{"confirm":true}'});toast(`已清理 ${r.cleared} 条缓存`)}catch(e){toast(e.message,true)}};
async function load(){try{const [overview,quotas,events,settings]=await Promise.all([api('/__admin/api/overview'),api('/__admin/api/quotas'),api('/__admin/api/events?limit=100'),api('/__admin/api/settings')]);state={overview,quotas,events,settings};renderOverview();renderQuotas();renderEvents();renderSettings();$('#updated').textContent=`更新于 ${new Date().toLocaleTimeString('zh-CN',displayTime)}`}catch(e){toast(e.message,true)}}
$('#refresh').onclick=load;window.addEventListener('resize',()=>state.overview&&renderChart(state.overview.trend||[]));nav(location.hash.slice(1)||'overview');load();setInterval(load,60000);
